INSERT OR REPLACE INTO grants (
      wordpress_id, title, excerpt, status, 
      created_at, updated_at,
      max_amount_display, max_amount_numeric,
      deadline_display, deadline_date,
      organization, organization_type, grant_target,
      application_method, contact_info, official_url,
      target_prefecture_code, prefecture_name, target_municipality,
      regional_limitation, application_status,
      categories, tags
    ) VALUES (
      1761111011644199,
      '【北山村】最大50万円！ホームページ制作に使える小規模事業者持続化補助金を徹底解説',
      '和歌山県北山村の小規模事業者必見！最大50万円（補助率1/2）が支援される「小規模事業者持続化補助金」を徹底解説。ホームページ制作やWeb広告、IT導入に活用できます。申請の鍵となる商工会との連携方法や採択のポイントも紹介。',
      'publish',
      '2025-10-22T05:30:12.915Z',
      '2025-10-22T05:30:12.915Z',
      '最大50万円',
      500000,
      '詳細は公式サイトにて要確認（※参考：令和7年度の募集情報に基づく）',
      '2026-03-31',
      '和歌山県北山村',
      'city',
      '北山村内に事業所を有し、村税等の滞納がなく、北山村商工会の会員である小規模事業者。',
      '北山村役場 産業建設課 TEL：0735-49-2331（代表） ※申請相談はまず北山村商工会へご連絡ください。',
      'https://www.vill.kitayama.wakayama.jp/jigyousya/',
      'municipality_only',
      '30',
      '和歌山県',
      '東牟婁郡北山村',
      'upcoming',
      '和歌山県',
      '["ホームページ制作","Web広告","多言語対応","業務効率化","キャッシュレス","ECサイト"]',
      '["https://www.vill.kitayama.wakayama.jp/jigyousya/"]'
    );